server:
  port: 8080

spring:
  application:
    name: route-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

map:
  provider: mapbox
  api-key: dummy-key
  base-url: https://api.mapbox.com
