server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/trafine_db
    username: trafine
    password: trafinepwd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: user-service
